<script setup lang="ts">
import {
  Activity,
  ArrowDownToLine,
  ArrowUpFromLine,
  Braces,
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  Copy,
  Cpu,
  FileStack,
  FlaskConical,
  Gauge,
  GitFork,
  Layers,
  ListChecks,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Menu,
  Moon,
  MoreVertical,
  Pencil,
  Plus,
  RotateCcw,
  Send,
  ShieldAlert,
  Square,
  Sun,
  Terminal,
  Trash2,
  Wrench,
  X,
} from "lucide-vue-next";

const props = defineProps<{
  name: string;
}>();

const icons: Record<string, unknown> = {
  "i-lucide-activity": Activity,
  "i-lucide-arrow-down-to-line": ArrowDownToLine,
  "i-lucide-arrow-up-from-line": ArrowUpFromLine,
  "i-lucide-brain": Brain,
  "i-lucide-braces": Braces,
  "i-lucide-check": Check,
  "i-lucide-chevron-down": ChevronDown,
  "i-lucide-chevron-right": ChevronRight,
  "i-lucide-circle": Circle,
  "i-lucide-circle-alert": CircleAlert,
  "i-lucide-copy": Copy,
  "i-lucide-cpu": Cpu,
  "i-lucide-file-stack": FileStack,
  "i-lucide-flask-conical": FlaskConical,
  "i-lucide-gauge": Gauge,
  "i-lucide-git-fork": GitFork,
  "i-lucide-layers": Layers,
  "i-lucide-list-checks": ListChecks,
  "i-lucide-loader-circle": LoaderCircle,
  "i-lucide-lock": Lock,
  "i-lucide-log-in": LogIn,
  "i-lucide-log-out": LogOut,
  "i-lucide-menu": Menu,
  "i-lucide-moon": Moon,
  "i-lucide-more-vertical": MoreVertical,
  "i-lucide-pencil": Pencil,
  "i-lucide-plus": Plus,
  "i-lucide-rotate-ccw": RotateCcw,
  "i-lucide-send": Send,
  "i-lucide-shield-alert": ShieldAlert,
  "i-lucide-square": Square,
  "i-lucide-sun": Sun,
  "i-lucide-terminal": Terminal,
  "i-lucide-trash-2": Trash2,
  "i-lucide-wrench": Wrench,
  "i-lucide-x": X,
};
</script>

<template>
  <component :is="icons[props.name] || Circle" aria-hidden="true" />
</template>
